<script setup lang="ts">
import { computed } from 'vue'
import { useData, withBase } from 'vitepress'

interface Props {
    /** 左侧图片路径（相对于 public 目录） */
    image?: string
    /** 标题 */
    title?: string
    /** 副标题 */
    subtitle?: string
    /** 正文说明 */
    text?: string
    /** 提示级别，决定左侧色条颜色：notice / content / serious */
    type?: 'notice' | 'content' | 'serious'
}

const props = withDefaults(defineProps<Props>(), {
    image: '/images/help-us.png',
    subtitle: ' ',
    type: 'content',
})

/** 按语言提供默认文案，未显式传入 title/text 时按当前 locale 回退 */
const messages = {
    'zh-CN': {
        title: '帮助我们完善这个文档！',
        text: '这篇文档是AI生成的，虽然大面上可能没有问题，但可能存在过时或者错误。希望您可以帮助我们改进它！',
    },
    'en-US': {
        title: 'Help us improve this page!',
        text: 'This page was generated by AI. Although it may be accurate in general, it could be outdated or contain errors. We would appreciate your help making it better!',
    },
} as const

const { lang } = useData()

const fallback = computed(() =>
    lang.value?.toLowerCase().startsWith('zh') ? messages['zh-CN'] : messages['en-US'],
)

const resolvedTitle = computed(() => props.title ?? fallback.value.title)
const resolvedText = computed(() => props.text ?? fallback.value.text)
</script>


<template>
    <!-- MediaWiki ambox（文章信息框）风格提示 -->
    <div class="ambox" :class="`ambox--${props.type}`" role="note">
        <div class="ambox__image">
            <img class="no-zoom" :src="withBase(props.image)" alt="" loading="lazy" />
        </div>
        <div class="ambox__text">
            <p class="ambox__heading">
                <span class="ambox__title">
                    <slot name="title">{{ resolvedTitle }}</slot>
                </span>
                <span class="ambox__sep" aria-hidden="true"> </span>
                <span class="ambox__subtitle">
                    <slot name="subtitle">{{ props.subtitle }}</slot>
                </span>
            </p>
            <p class="ambox__body">
                <slot>{{ resolvedText }}</slot>
            </p>
        </div>
    </div>
</template>

